import cv2

BACK_BUTTON_TEMPLATE = cv2.imread("assets/buttons/back_btn.png", cv2.IMREAD_COLOR)
CANCEL_BUTTON_TEMPLATE = cv2.imread("assets/buttons/cancel_btn.png", cv2.IMREAD_COLOR)
CLAW_BUTTON_TEMPLATE = cv2.imread("assets/buttons/claw.png", cv2.IMREAD_COLOR)
CLOSE_BUTTON_TEMPLATE = cv2.imread("assets/buttons/close.png", cv2.IMREAD_COLOR)
CONFIRM_BUTTON_TEMPLATE = cv2.imread("assets/buttons/confirm.png", cv2.IMREAD_COLOR)
INSPIRATION_BUTTON_TEMPLATE = cv2.imread("assets/buttons/inspiration_btn.png", cv2.IMREAD_COLOR)
INFIRMARY_BUTTON_TEMPLATE = cv2.imread("assets/buttons/infirmary_btn2.png", cv2.IMREAD_COLOR)
LEARN_BUTTON_TEMPLATE = cv2.imread("assets/buttons/learn.png", cv2.IMREAD_COLOR)
NEXT_BUTTON_TEMPLATE = cv2.imread("assets/buttons/next_btn.png", cv2.IMREAD_COLOR)
NEXT_2_BUTTON_TEMPLATE = cv2.imread("assets/buttons/next2_btn.png", cv2.IMREAD_COLOR)
OK_BUTTON_TEMPLATE = cv2.imread("assets/buttons/ok_btn.png", cv2.IMREAD_COLOR)
RACE_BUTTON_TEMPLATE = cv2.imread("assets/buttons/race_btn.png", cv2.IMREAD_COLOR)
RACES_BUTTON_TEMPLATE = cv2.imread("assets/buttons/races_btn.png", cv2.IMREAD_COLOR)
RACE_DAY_BUTTON_TEMPLATE = cv2.imread("assets/buttons/race_day_btn.png", cv2.IMREAD_COLOR)
RACE_URA_TEMPLATE = cv2.imread("assets/buttons/race_ura.png", cv2.IMREAD_COLOR)
RECREATION_BUTTON_TEMPLATE = cv2.imread("assets/buttons/recreation_btn.png", cv2.IMREAD_COLOR)
REST_BUTTON_TEMPLATE = cv2.imread("assets/buttons/rest_btn.png", cv2.IMREAD_COLOR)
REST_SUMMER_BUTTON_TEMPLATE = cv2.imread("assets/buttons/rest_summer_btn.png", cv2.IMREAD_COLOR)
SKILL_UP_BUTTON_TEMPLATE = cv2.imread("assets/buttons/skill_up.png", cv2.IMREAD_COLOR)
SKILLS_BUTTON_TEMPLATE = cv2.imread("assets/buttons/skills_btn.png", cv2.IMREAD_COLOR)
STRATEGY_BUTTON_TEMPLATE = cv2.imread("assets/buttons/strategy_change.png", cv2.IMREAD_COLOR)
TRAINING_BUTTON_TEMPLATE = cv2.imread("assets/buttons/training_btn.png", cv2.IMREAD_COLOR)
TRY_AGAIN_BUTTON_TEMPLATE = cv2.imread("assets/buttons/try_again_btn.png", cv2.IMREAD_COLOR)
VIEW_RESULTS_BUTTON_TEMPLATE = cv2.imread("assets/buttons/view_results.png", cv2.IMREAD_COLOR)

CLOCK_TEMPLATE = cv2.imread("assets/icons/clock.png", cv2.IMREAD_COLOR)
EVENT_CHOICE_1_TEMPLATE = cv2.imread("assets/icons/event_choice_1.png", cv2.IMREAD_COLOR)
HINT_TEMPLATE = cv2.imread("assets/icons/hint.png", cv2.IMREAD_COLOR)

G1_RACE_TEMPLATE = cv2.imread("assets/ui/g1_race.png", cv2.IMREAD_COLOR)
MATCH_TRACK_TEMPLATE = cv2.imread("assets/ui/match_track.png", cv2.IMREAD_COLOR)
TAZUNA_HINT_TEMPLATE = cv2.imread("assets/ui/tazuna_hint.png", cv2.IMREAD_COLOR)
